import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoadingWrapper from "../components/LoadingWrapper";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/homePage.svg" as="image" />
        <link rel="preload" href="/productivity.svg" as="image" />
        <link rel="preload" href="/Description.svg" as="image" />
        <link rel="preload" href="/Punchline.svg" as="image" />
      </head>
      <body
        className={`${inter.variable} antialiased p-0 m-0 select-none font-inter bg-[#030012] overflow-x-hidden w-full`}
        style={{
          WebkitTouchCallout: 'none',
          WebkitUserSelect: 'none',
          MozUserSelect: 'none',
          msUserSelect: 'none',
          userSelect: 'none',
          maxWidth: '100vw'
        } as React.CSSProperties}
      >
        <LoadingWrapper>
          <Navbar />
          {children}
          <Footer />
        </LoadingWrapper>
      </body>
    </html>
  );
}
